-- =============================================================================
-- 0004_auth_persistence.sql
-- =============================================================================
--
-- Chunk 3 of the auth + persistence build.
--
-- Adds:
--   1. profiles               — keyed by auth.users(id), auto-populated via trigger
--   2. matters                — user workspaces; soft-delete via archived_at
--   3. conversations          — chat threads; matter_id nullable (standalone or in-matter)
--   4. messages               — chat messages; inherits access from conversations
--   5. handle_new_user() function + on_auth_user_created trigger
--   6. RLS enable + 4 policies (SELECT/INSERT/UPDATE/DELETE) per user-scoped table
--
-- THIS FILE IS HAND-WRITTEN — IT WAS NOT GENERATED BY DRIZZLE-KIT.
-- See README "Manual migration: why and how" for context on why, and the steps
-- you need to take if drizzle-kit ever complains about it.
--
-- Statement breakpoints (-->> statement-breakpoint) tell drizzle-kit's
-- migrator to split this file into separate statements when executing.
-- Postgres can technically take the whole file as one transaction, but
-- drizzle-kit's `db:migrate` runner runs statements one at a time and
-- expects these markers.
--
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. profiles
-- ---------------------------------------------------------------------------
--
-- One row per user. The id IS the auth.users(id) — same UUID, propagated via
-- the handle_new_user() trigger. ON DELETE CASCADE means if Supabase deletes
-- an auth.users row (rare, but possible), the profile and all downstream
-- data cascades away cleanly.
--
-- Why not just read from auth.users directly?
--   - auth.users is owned by Supabase; we shouldn't extend it.
--   - We want app-specific fields (firm_name, role) that don't belong there.
--   - It cleanly separates "identity" (auth.users) from "profile" (public.profiles).
--
-- The trigger that populates this is defined below.
--
CREATE TABLE "profiles" (
  "id" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "full_name" text,
  "firm_name" text,
  "role" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. matters
-- ---------------------------------------------------------------------------
--
-- A user's case workspace. Soft-deleted via archived_at (NULL = active row,
-- non-NULL = archived; queries filter on `archived_at IS NULL` to hide them).
--
-- Status is text + CHECK constraint (NOT a Postgres enum). The 6 statuses
-- match what the UI's StatusMenu component already shows — keep them in sync
-- with app/(app)/matters/_data/mock-matters.ts > MATTER_STATUSES.
--
-- Index choices:
--   - (user_id)              — for "show me all my matters"
--   - (user_id, status)      — for filtered views ("show me my active matters")
--   - (user_id, archived_at) — for the default "non-archived" filter
--
CREATE TABLE "matters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "name" text NOT NULL,
  "client" text,
  "description" text,
  "status" text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'on-hold', 'awaiting-client', 'in-hearing', 'settled', 'closed')),
  "notes" text,
  "archived_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "matters_user_id_idx" ON "matters" ("user_id");
--> statement-breakpoint
CREATE INDEX "matters_user_id_status_idx" ON "matters" ("user_id", "status");
--> statement-breakpoint
CREATE INDEX "matters_user_id_archived_at_idx" ON "matters" ("user_id", "archived_at");
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. conversations
-- ---------------------------------------------------------------------------
--
-- One row per chat thread. matter_id is NULLABLE:
--   - NULL          → standalone /chat conversation, lives at /chat?conversationId=...
--   - non-NULL      → conversation belongs to a matter, shown inside the matter workspace
--
-- ON DELETE CASCADE on matter_id: if a matter is hard-deleted, its conversations go too.
-- (We don't hard-delete matters via the UI — that's CASCADE behaviour for safety,
-- not the default UX path.)
--
-- We also have user_id directly here (not just via matter_id) because:
--   - Standalone conversations have no matter
--   - Direct user_id makes RLS policies simpler and faster
--   - Faster "show me all this user's recent conversations" queries
--
CREATE TABLE "conversations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "matter_id" uuid REFERENCES "matters"(id) ON DELETE CASCADE,
  "title" text,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "conversations_user_id_idx" ON "conversations" ("user_id");
--> statement-breakpoint
CREATE INDEX "conversations_matter_id_idx" ON "conversations" ("matter_id");
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. messages
-- ---------------------------------------------------------------------------
--
-- One row per chat message. Belongs to exactly one conversation.
-- Role is text + CHECK (not enum) to stay consistent with status above.
--
-- citations is JSONB and stores the FULL hit shape from semanticSearch():
--   [{ index, judgmentId, caseName, citation, paragraphNumber, paragraphText, similarity }, ...]
--
-- This is intentional — see the README's "Why store full citations" section.
-- TL;DR: snapshot semantics. If a judgment is amended later, the lawyer's
-- past research note still shows what was true at the time it was written.
--
-- No user_id column here — access is mediated entirely through the
-- conversation's user_id, which the RLS policy enforces. This is cleaner
-- than denormalising user_id onto every message.
--
CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "conversation_id" uuid NOT NULL REFERENCES "conversations"(id) ON DELETE CASCADE,
  "role" text NOT NULL CHECK (role IN ('user', 'assistant')),
  "content" text NOT NULL,
  "citations" jsonb,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX "messages_conversation_id_idx" ON "messages" ("conversation_id");
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. handle_new_user() function + trigger
-- ---------------------------------------------------------------------------
--
-- When Supabase Auth creates a new user (via password sign-up OR OAuth),
-- the BEFORE-INSERT row hits auth.users. This trigger fires AFTER that insert
-- and creates the matching row in public.profiles. No app-layer code needed.
--
-- SECURITY DEFINER is essential: the function runs with the privileges of the
-- function's owner (postgres), not the caller (Supabase Auth's internal user).
-- Without SECURITY DEFINER, the trigger would fail with permission errors
-- because Supabase Auth doesn't have INSERT on public.profiles.
--
-- `set search_path = public` is a hardening measure: SECURITY DEFINER functions
-- should always pin their search_path to prevent search-path injection attacks.
--
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id) VALUES (NEW.id);
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. Row Level Security (defense-in-depth backstop)
-- ---------------------------------------------------------------------------
--
-- IMPORTANT context, repeated here because it's critical:
--
-- Drizzle connects as the `postgres` role (Supabase's transaction pooler
-- credentials), which BYPASSES RLS. So in normal operation, our explicit
-- `WHERE user_id = $userId` filters in the Drizzle queries are what enforce
-- access control.
--
-- These RLS policies are a SAFETY NET. If a query somewhere forgets a
-- user_id filter, AND that query runs as a Supabase-authenticated client
-- (i.e. via supabase-js with the user's JWT), RLS prevents data leakage.
--
-- We enable RLS even though our path doesn't use it day-to-day because:
--   1. We may add browser-side Supabase queries later (e.g. realtime
--      subscriptions). Those WILL respect RLS.
--   2. Supabase shows "RLS disabled" warnings in the dashboard for tables
--      without it, and we don't want to teach ourselves to ignore them.
--   3. Defense in depth costs nothing here.
--
-- The policies use auth.uid() — a Supabase-provided function that returns
-- the authenticated user's UUID, or NULL if unauthenticated. Coupled with
-- USING / WITH CHECK clauses, this is the standard Supabase RLS pattern.
--

ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "profiles_select_own" ON "profiles"
  FOR SELECT USING (auth.uid() = id);
--> statement-breakpoint
CREATE POLICY "profiles_insert_own" ON "profiles"
  FOR INSERT WITH CHECK (auth.uid() = id);
--> statement-breakpoint
CREATE POLICY "profiles_update_own" ON "profiles"
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
--> statement-breakpoint
CREATE POLICY "profiles_delete_own" ON "profiles"
  FOR DELETE USING (auth.uid() = id);
--> statement-breakpoint

ALTER TABLE "matters" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "matters_select_own" ON "matters"
  FOR SELECT USING (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "matters_insert_own" ON "matters"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "matters_update_own" ON "matters"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "matters_delete_own" ON "matters"
  FOR DELETE USING (auth.uid() = user_id);
--> statement-breakpoint

ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "conversations_select_own" ON "conversations"
  FOR SELECT USING (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "conversations_insert_own" ON "conversations"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "conversations_update_own" ON "conversations"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "conversations_delete_own" ON "conversations"
  FOR DELETE USING (auth.uid() = user_id);
--> statement-breakpoint

-- Messages: access inherited from the parent conversation. A user can read,
-- write, modify, or delete a message IFF the parent conversation belongs to
-- them. This is enforced via EXISTS subquery, which uses the messages_
-- conversation_id_idx index for fast lookup.
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "messages_select_via_conversation" ON "messages"
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM "conversations"
      WHERE "conversations"."id" = "messages"."conversation_id"
        AND "conversations"."user_id" = auth.uid()
    )
  );
--> statement-breakpoint
CREATE POLICY "messages_insert_via_conversation" ON "messages"
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM "conversations"
      WHERE "conversations"."id" = "messages"."conversation_id"
        AND "conversations"."user_id" = auth.uid()
    )
  );
--> statement-breakpoint
CREATE POLICY "messages_update_via_conversation" ON "messages"
  FOR UPDATE
    USING (
      EXISTS (
        SELECT 1 FROM "conversations"
        WHERE "conversations"."id" = "messages"."conversation_id"
          AND "conversations"."user_id" = auth.uid()
      )
    )
    WITH CHECK (
      EXISTS (
        SELECT 1 FROM "conversations"
        WHERE "conversations"."id" = "messages"."conversation_id"
          AND "conversations"."user_id" = auth.uid()
      )
    );
--> statement-breakpoint
CREATE POLICY "messages_delete_via_conversation" ON "messages"
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM "conversations"
      WHERE "conversations"."id" = "messages"."conversation_id"
        AND "conversations"."user_id" = auth.uid()
    )
  );
