-- =============================================================================
-- 0005_files.sql — Chunk 6: Files foundation
-- =============================================================================
--
-- HAND-WRITTEN MIGRATION — NOT GENERATED BY DRIZZLE-KIT.
-- Same approach as 0004_auth_persistence.sql: FKs to auth.users live in raw
-- SQL, RLS policies live here, and the trigger/policy syntax couldn't be
-- expressed via Drizzle's TS API anyway.
--
-- Statement breakpoints (--> statement-breakpoint) tell drizzle-kit's
-- migrator to split this file into separate statements when executing.
--
--
-- ===========================================================================
-- SUPABASE STORAGE BUCKET SETUP (MANUAL DASHBOARD STEP — REQUIRED)
-- ===========================================================================
--
-- This migration creates the database schema and RLS policies, but the
-- Storage BUCKET itself must be created via the Supabase dashboard. The
-- bucket is what holds the actual file bytes; storage.objects (which we
-- DO write RLS policies for below) is just the metadata table.
--
-- DASHBOARD STEPS (do these BEFORE running `npm run db:migrate`):
--
-- 1. Open the Supabase project dashboard
-- 2. Storage (left sidebar) → "New bucket"
-- 3. Name:                case-files
-- 4. Public bucket:       LEAVE UNCHECKED (private)
-- 5. Additional settings:
--    a. Restrict file size: ENABLE
--       Set to: 10000000 bytes (= 10 MB decimal — matches MAX_FILE_BYTES
--                                in lib/files/types.ts)
--    b. Allowed MIME types: ENABLE
--       Add three entries (one per line):
--         application/pdf
--         application/vnd.openxmlformats-officedocument.wordprocessingml.document
--         text/plain
-- 6. Save
--
-- CORS: default settings work for direct-from-browser signed URL uploads
-- from the same origin. No changes needed.
--
-- RLS policies on storage.objects are applied by THIS migration's SQL —
-- you do NOT need to add policies via the dashboard. If you accidentally
-- add policies via the dashboard, they will conflict with the ones below.
--
-- After creating the bucket, run:
--   npm run db:migrate
--
-- ===========================================================================
--
-- WHY MIME TYPE + SIZE LIMITS ARE ENFORCED IN BOTH PLACES (BUCKET + APP):
--
--   Bucket-level limits are Supabase's last line of defence — they reject
--   uploads that somehow bypass our server-side validation (e.g. a signed
--   URL being reused for a different file). App-level validation is the
--   first line — it gives lawyers a clear error message before any upload
--   network traffic happens. Both layers must agree, which is why the
--   constants live in ONE place (lib/files/types.ts) and are referenced
--   from the dashboard config above + the server action validation.
--
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. files
-- ---------------------------------------------------------------------------
--
-- Mirrors the matters table pattern. Notes:
--
--   - user_id is denormalised onto this table (not derived via matter_id).
--     Same rationale as conversations.user_id: makes RLS simpler, makes
--     "all this user's files" queries direct, costs one extra column.
--
--   - storage_path is the canonical pointer into Supabase Storage. Format:
--       {user_id}/{matter_id}/{file_id}{extension}
--     The user_id prefix is what the storage RLS policies key on (see
--     storage.foldername(name)[1] = auth.uid()::text below).
--
--   - anthropic_file_id lives directly on this row. 1:1 relationship with
--     the file; no benefit to a separate cache table. Set on first read
--     (Chunk 7); cleared on soft-delete.
--
--   - ai_readable is computed ONCE at upload time and stored. We don't
--     re-evaluate per-read. Page count and MIME type don't change.
--
--   - No "status" enum column. Failed uploads result in a row that exists
--     in `files` but has no corresponding storage object. The "list files"
--     query detects orphans on read; a janitor (future) sweeps them.
--
--   - filename is what the lawyer typed — preserves spaces, unicode,
--     parens, em-dashes. We sanitise (strip control chars, cap 255)
--     in lib/db/queries/files.ts. The original NEVER hits storage_path,
--     so unicode/spaces in filenames don't break URL signing.
--
CREATE TABLE "files" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "matter_id" uuid NOT NULL REFERENCES "matters"(id) ON DELETE CASCADE,
  "filename" text NOT NULL,
  "storage_path" text NOT NULL,
  "mime_type" text NOT NULL,
  "file_size" integer NOT NULL,
  "page_count" integer,
  "ai_readable" boolean NOT NULL DEFAULT true,
  "ai_readable_reason" text,
  "anthropic_file_id" text,
  "deleted_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- (matter_id, deleted_at) — hot path: "list non-deleted files in this matter"
CREATE INDEX "files_matter_id_deleted_at_idx"
  ON "files" ("matter_id", "deleted_at");
--> statement-breakpoint
-- (user_id, deleted_at) — for "all this user's files" listings
CREATE INDEX "files_user_id_deleted_at_idx"
  ON "files" ("user_id", "deleted_at");
--> statement-breakpoint
-- (user_id, matter_id) — for the quota query SUM(file_size)
CREATE INDEX "files_user_id_matter_id_idx"
  ON "files" ("user_id", "matter_id");
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. file_tags
-- ---------------------------------------------------------------------------
--
-- Many-to-many with no separate "tags" master table. Reasoning: lawyers
-- type free-form tags, and the autocomplete is built from
-- SELECT DISTINCT tag_label FROM file_tags WHERE user_id = ... — a master
-- table would just add a join with no actual benefit.
--
-- `tag` is normalised (lowercase, trim) for matching/deduping.
-- `tag_label` is the display form preserving how the lawyer typed it.
-- So "Affidavit" / "affidavit" / "AFFIDAVIT" all dedupe but the lawyer
-- sees their original capitalisation.
--
-- Note: file_tags rows inherit access from the parent file via the RLS
-- policy below (EXISTS subquery on files.user_id = auth.uid()). No
-- denormalised user_id here — the file_id is sufficient.
--
CREATE TABLE "file_tags" (
  "file_id" uuid NOT NULL REFERENCES "files"(id) ON DELETE CASCADE,
  "tag" text NOT NULL,
  "tag_label" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY ("file_id", "tag")
);
--> statement-breakpoint
-- For filter-by-tag queries and autocomplete distinct lookups.
CREATE INDEX "file_tags_tag_idx" ON "file_tags" ("tag");
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. updated_at trigger for files
-- ---------------------------------------------------------------------------
--
-- Files get edited (tag changes, soft-delete, restore). Bump updated_at
-- automatically via trigger so the queries layer doesn't have to remember.
--
-- This is the first table in the schema to use such a trigger; matters/
-- conversations have updated_at columns but rely on explicit query-side
-- `set({ updatedAt: new Date() })`. We could refactor those later to use
-- triggers too, but that's out of scope for Chunk 6.
--
CREATE OR REPLACE FUNCTION public.touch_files_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER files_touch_updated_at
  BEFORE UPDATE ON "files"
  FOR EACH ROW EXECUTE FUNCTION public.touch_files_updated_at();
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. Row Level Security on public.files
-- ---------------------------------------------------------------------------
--
-- Same backstop reasoning as matters/conversations: Drizzle connects as
-- the postgres role and bypasses RLS, so day-to-day protection is via
-- explicit where(eq(files.userId, userId)) in lib/db/queries/files.ts.
-- These policies catch any browser-side Supabase queries we might add
-- later (e.g. realtime subscriptions).
--
ALTER TABLE "files" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "files_select_own" ON "files"
  FOR SELECT USING (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "files_insert_own" ON "files"
  FOR INSERT WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "files_update_own" ON "files"
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
--> statement-breakpoint
CREATE POLICY "files_delete_own" ON "files"
  FOR DELETE USING (auth.uid() = user_id);
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. Row Level Security on public.file_tags
-- ---------------------------------------------------------------------------
--
-- Access mediated through the parent file's user_id (same pattern as
-- messages via conversations). No update policy — tags are
-- delete-and-insert, not in-place editable.
--
ALTER TABLE "file_tags" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "file_tags_select_via_file" ON "file_tags"
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM "files"
      WHERE "files"."id" = "file_tags"."file_id"
        AND "files"."user_id" = auth.uid()
    )
  );
--> statement-breakpoint
CREATE POLICY "file_tags_insert_via_file" ON "file_tags"
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM "files"
      WHERE "files"."id" = "file_tags"."file_id"
        AND "files"."user_id" = auth.uid()
    )
  );
--> statement-breakpoint
CREATE POLICY "file_tags_delete_via_file" ON "file_tags"
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM "files"
      WHERE "files"."id" = "file_tags"."file_id"
        AND "files"."user_id" = auth.uid()
    )
  );
--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. Row Level Security on storage.objects (for the case-files bucket)
-- ---------------------------------------------------------------------------
--
-- Path-based scoping: the first segment of the object name is the user_id.
-- storage.foldername(name) returns an array of path segments;
-- (storage.foldername(name))[1] is the first segment.
--
-- This is the standard Supabase pattern. Signed URLs bypass these policies
-- (they're capability tokens) — we always generate signed URLs server-side
-- AFTER ownership has been verified in our Drizzle layer.
--
-- Note: storage.objects has RLS enabled by default in modern Supabase
-- projects. We just add our policies; we don't ALTER TABLE ... ENABLE RLS.
--
CREATE POLICY "case_files_select_own" ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'case-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
--> statement-breakpoint
CREATE POLICY "case_files_insert_own" ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'case-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
--> statement-breakpoint
CREATE POLICY "case_files_update_own" ON storage.objects
  FOR UPDATE
  USING (
    bucket_id = 'case-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'case-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
--> statement-breakpoint
CREATE POLICY "case_files_delete_own" ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'case-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
