// scripts/outreach/chambers-registry.ts
//
// The target registry: NSW barristers' chambers that publish their members'
// contact details on their OWN website.
//
// WHY THIS FILE EXISTS IN THIS SHAPE
// ----------------------------------
// The obvious source — the NSW Bar Association "Find a Barrister" directory —
// is off-limits. Its terms state:
//
//   "Any use of this website other than for personal research is strictly
//    forbidden."
//   "The use of website scraping, data harvesting, or search spidering for any
//    purpose other than to supply search query results to end-users is
//    strictly forbidden."
//   — https://nswbar.asn.au/disclaimers/find-a-barrister
//
// Nothing in this registry is sourced from nswbar.asn.au. Every entry is a
// chambers' own site, where the barrister (or their set, on their behalf)
// has published the address. That distinction is what supports inferred
// consent under Spam Act 2003 (Cth) Sch 2 cl 4(2)(c): it must be
// "reasonable to assume that the publication occurred with the agreement of"
// the individual.
//
// Chambers discovered via general web search and the NSW Barristers' Clerks
// Association public member roll (https://www.nswbca.org/association-members).

import type { ChambersTarget } from './types';

export const CHAMBERS: ChambersTarget[] = [
  // ---------------------------------------------------------------------
  // TIER 1 — emails on the listing page. One fetch per set, no profile hop.
  // ---------------------------------------------------------------------
  {
    slug: 'eleven-wentworth',
    name: 'Eleven Wentworth',
    url: 'https://elevenwentworth.com',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/portfolio/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 47,
    emailExposure: 'listing',
    renderer: 'static',
    notes: 'Highest yield per request in the whole registry — the index carries all ~47 addresses. Grouped by seniority.',
  },
  {
    slug: 'sixth-floor-selborne-wentworth',
    name: 'Sixth Floor Selborne Wentworth',
    url: 'https://sixthfloor.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 57,
    emailExposure: 'listing',
    renderer: 'js',
    notes: 'Listing lazy-loads ("Loading.."). Needs the Playwright path to get the full set. 19 SC.',
  },
  {
    slug: '2-selborne',
    name: 'Second Floor Selborne',
    url: 'https://www.2selborne.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 20,
    emailExposure: 'listing',
    renderer: 'static',
    notes: 'Paginated 9/page. Mixed email domains: @selbornechambers.com.au and @2selborne.com.au.',
  },
  {
    slug: 'state-chambers',
    name: 'State Chambers',
    url: 'https://statechambers.net',
    listingPaths: ['/barristers/'],
    profilePattern: '^/[a-z0-9-]+-(sc|kc)?/?$',
    region: 'sydney-cbd',
    approxCount: 30,
    emailExposure: 'listing',
    renderer: 'static',
    focus: ['employment', 'public law', 'commercial', 'common law', 'insurance', 'WHS'],
    notes: 'Flat profile URLs at root — scope link discovery to the listing page, do not guess by URL shape. firstname.lastname@statechambers.net.',
  },
  {
    slug: 'greenway',
    name: 'Greenway Chambers',
    url: 'https://www.greenway.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 50,
    emailExposure: 'listing-cf',
    renderer: 'static',
    focus: ['building & construction', 'commercial & equity', 'employment & IR', 'planning & environment', 'family'],
    notes: 'Cloudflare email-protection on the listing — decoded by decodeCloudflareEmail(). Shows year of call AND silk year.',
  },
  {
    slug: 'newcastle-chambers',
    name: 'Newcastle Chambers',
    url: 'https://newcastlechambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'newcastle',
    approxCount: 10,
    emailExposure: 'listing',
    renderer: 'static',
    focus: ['commercial', 'common law/PI', 'criminal', 'family', 'industrial/employment', 'inquests', 'WHS'],
    notes: 'Best email availability of any regional set. First formal chambers in Newcastle (1980s). Strong ICP: regional generalists least likely to hold Westlaw/Lexis seats.',
  },
  {
    slug: 'evatt-chambers',
    name: 'Evatt Chambers',
    url: 'https://www.evattchambers.com',
    listingPaths: ['/barristers.html'],
    profilePattern: '^/barristers\\.html$',
    region: 'newcastle',
    approxCount: 2,
    emailExposure: 'listing',
    renderer: 'static',
    focus: ['criminal'],
    notes: 'Single page, both addresses published.',
  },
  {
    slug: 'wollongong-chambers',
    name: 'Wollongong Chambers',
    url: 'https://www.wollongongchambers.com.au',
    listingPaths: ['/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'wollongong',
    approxCount: 1,
    emailExposure: 'listing',
    renderer: 'static',
    focus: ['common law/PI', 'commercial', 'family provision', 'family', 'insurance', 'IR'],
  },

  // ---------------------------------------------------------------------
  // TIER 2 — clean WordPress /barrister/<slug>/ pattern. Index then hop.
  // These are the bulk of the corpus and all behave the same way.
  // ---------------------------------------------------------------------
  {
    slug: 'banco',
    name: 'Banco Chambers',
    url: 'https://www.banco.net.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 70,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Gold-standard target: profile carries direct email, direct phone, year of call and practice areas. 1 Bligh St.',
  },
  {
    slug: 'frederick-jordan',
    name: 'Frederick Jordan Chambers',
    url: 'https://fjc.net.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 130,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Largest set found. 13 SC. Practice-area filter facets on the listing. firstname.lastname@fjc.net.au.',
  },
  {
    slug: 'maurice-byers',
    name: 'Maurice Byers Chambers',
    url: 'https://mauricebyers.com',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 68,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '14 SC, 54 junior counsel. Admission + silk years on profile. L60, 25 Martin Place.',
  },
  {
    slug: '12-wentworth-selborne',
    name: 'Twelve Wentworth Selborne',
    url: 'https://12thfloor.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 67,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Nickname-style local parts (e.g. fordo@12thfloor.com.au) — do not synthesise addresses for this set, read them.',
  },
  {
    slug: 'tenth-floor',
    name: 'Tenth Floor Chambers',
    url: 'https://tenthfloor.org',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 40,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Profiles list ~15 practice areas + "Admitted to Bar" year. Surname-only local parts.',
  },
  {
    slug: 'ground-floor-wentworth',
    name: 'Ground Floor Wentworth Chambers',
    url: 'https://www.wentworthchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 40,
    emailExposure: 'profile',
    renderer: 'static',
  },
  {
    slug: 'new-chambers',
    name: 'New Chambers',
    url: 'https://newchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 41,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '15 SC, 23 junior, 2 readers, 13 associates. Deep practice-area taxonomy on profiles.',
  },
  {
    slug: 'wardell',
    name: 'Wardell Chambers',
    url: 'https://wardellchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 32,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '12 practice areas + year of call on profile.',
  },
  {
    slug: '5-wentworth',
    name: 'Five Wentworth',
    url: 'https://www.5wentworth.com',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 40,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '9 KC/SC. firstname.lastname@5wentworth.com + direct DID.',
  },
  {
    slug: 'jack-shand',
    name: 'Jack Shand Chambers',
    url: 'https://jackshand.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 32,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '7 SC, 23 junior, 2 honorary. L55, 25 Martin Place.',
  },
  {
    slug: 'ninth-floor-selborne',
    name: 'Ninth Floor Selborne',
    url: 'https://9selborne.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 34,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Some members surname@selbornechambers.com.au; others route to clerk.',
  },
  {
    slug: '8-selborne',
    name: 'Eight Selborne',
    url: 'https://eightselborne.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 27,
    emailExposure: 'profile',
    renderer: 'static',
  },
  {
    slug: '4-selborne',
    name: 'Fourth Floor Selborne',
    url: 'https://www.4selborne.com.au',
    listingPaths: ['/counsel/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 26,
    emailExposure: 'profile',
    renderer: 'static',
    focus: ['family provision', 'equity', 'costs', 'commercial', 'insolvency'],
    notes: 'Listing at /counsel/, profiles at /barrister/ — the one site where those diverge.',
  },
  {
    slug: '13-wentworth',
    name: 'Thirteen Wentworth Chambers',
    url: 'https://13wentworth.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 40,
    emailExposure: 'profile',
    renderer: 'static',
  },
  {
    slug: '9-wentworth',
    name: 'Nine Wentworth Chambers',
    url: 'https://ninewentworth.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 39,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: '7 SC, 30 counsel, 2 readers.',
  },
  {
    slug: '3-wentworth',
    name: 'Third Floor Wentworth',
    url: 'https://www.3wentworth.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 21,
    emailExposure: 'clerk-only',
    renderer: 'static',
  },
  {
    slug: 'waratah',
    name: 'Waratah Chambers',
    url: 'https://waratahchambers.com.au',
    listingPaths: ['/barrister/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 27,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['family', 'care & protection', 'succession', 'ADVO'],
    notes: 'Largest dedicated family set. 175 Liverpool St.',
  },
  {
    slug: 'chalfont',
    name: 'Chalfont Chambers',
    url: 'https://chalfont.com.au',
    listingPaths: ['/barristers/', '/barristers/called/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 30,
    emailExposure: 'profile',
    renderer: 'static',
    notes: '/barristers/called/ is a by-year-of-call view — useful for seniority segmentation.',
  },
  {
    slug: 'coram',
    name: 'Coram Chambers',
    url: 'https://coramchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 21,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'NAME COLLISION: unrelated to coramchambers.co.uk (UK family set). Domain-check before matching.',
  },
  {
    slug: 'culwulla',
    name: 'Culwulla Chambers',
    url: 'https://culwulla.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 18,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Surname-first URL slugs (barnett-martha-sc).',
  },
  {
    slug: 'latham',
    name: 'Latham Chambers',
    url: 'https://www.lathamchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 11,
    emailExposure: 'profile',
    renderer: 'static',
  },
  {
    slug: 'nigel-bowen',
    name: 'Nigel Bowen Chambers',
    url: 'https://nigelbowen.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 30,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['IP', 'media & communications', 'competition & consumer', 'migration', 'environmental & planning'],
    notes: 'Federal Court-oriented. Strong fit for the HCA + Cth Acts half of the corpus.',
  },
  {
    slug: 'alinea',
    name: 'Alinea Chambers',
    url: 'https://www.alineachambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 18,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['commercial disputes', 'administrative/public', 'insolvency & restructuring'],
    notes: 'Newer set, Legal 500 Leading Set since 2022. Newer sets are still choosing tooling.',
  },
  {
    slug: '9-windeyer',
    name: 'Nine Windeyer Chambers',
    url: 'https://www.9windeyer.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 16,
    emailExposure: 'profile',
    renderer: 'static',
  },
  {
    slug: 'family-law-chambers',
    name: 'Family Law Chambers',
    url: 'https://www.familylawchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 13,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['family'],
  },
  {
    slug: 'hb-higgins',
    name: 'H.B. Higgins Chambers',
    url: 'https://www.hbhiggins.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 9,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['employment & industrial', 'WHS', 'administrative'],
    notes: 'RATE-LIMITS HARD — returned repeated 429s during discovery. perDomainDelayMs is raised for this host.',
  },
  {
    slug: '7-garfield-barwick',
    name: 'Seven Garfield Barwick Chambers',
    url: 'https://7gbc.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 31,
    emailExposure: 'clerk-only',
    renderer: 'static',
  },
  {
    slug: '11-garfield-barwick',
    name: 'Eleven Garfield Barwick Chambers',
    url: 'https://11gbc.chambers.net.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/(counsel|senior-counsel)/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 34,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Seniority is encoded in the URL path — free segmentation signal.',
  },

  // ---------------------------------------------------------------------
  // TIER 3 — idiosyncratic but cheap once the pattern is coded. Old static
  // sites with no JS at all.
  // ---------------------------------------------------------------------
  {
    slug: 'forbes',
    name: 'Forbes Chambers',
    url: 'https://www.forbeschambers.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+\\.html$',
    region: 'sydney-cbd',
    approxCount: 49,
    emailExposure: 'profile',
    renderer: 'static',
    focus: ['criminal', 'disciplinary', 'administrative', 'coronial'],
    notes: 'Largest criminal set in Australia. Flat .html files — cheapest crawl in the registry.',
  },
  {
    slug: 'martin-place',
    name: 'Martin Place Chambers',
    url: 'https://www.mpchambers.net.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z]+\\.html$',
    region: 'sydney-cbd',
    approxCount: 24,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Legacy static, initial+surname filenames (apickles.html). 8 SC, 11 senior junior, 5 junior.',
  },
  {
    slug: '6-windeyer',
    name: 'Sixth Floor Windeyer Chambers',
    url: 'https://www.6windeyer.com.au',
    listingPaths: ['/barristers.html', '/'],
    profilePattern: '^/[a-z_]+\\.html$',
    region: 'sydney-cbd',
    approxCount: 12,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Underscore slugs (vance_hughston_sc.html).',
  },
  {
    slug: 'marbury',
    name: 'Marbury Chambers',
    url: 'https://marburychambers.com.au',
    listingPaths: ['/index.php/barristers/', '/'],
    profilePattern: '^/index\\.php/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 12,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['native title', 'sports law', 'competition & consumer', 'tax'],
  },
  {
    slug: '6-st-james-hall',
    name: 'Six St James Hall Chambers',
    url: 'https://www.sixstjameshall.com.au',
    listingPaths: ['/6-st-james-hall-barristers/'],
    profilePattern: '^/6-st-james-hall-barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 36,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['appellate', 'commercial', 'employment', 'international law & human rights', 'public law'],
  },
  {
    slug: '11-st-james',
    name: 'Eleven St James Hall Chambers',
    url: 'https://11stjames.net.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 25,
    emailExposure: 'clerk-only',
    renderer: 'static',
  },
  {
    slug: '3-st-james-hall',
    name: 'Three St James Hall Chambers',
    url: 'https://3sjh.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 24,
    emailExposure: 'clerk-only',
    renderer: 'static',
  },
  {
    slug: '5-st-james',
    name: 'Fifth Floor St James Hall',
    url: 'https://5stjames.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 9,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Flat root slugs — scope to listing links only.',
  },
  {
    slug: 'tenth-floor-st-james',
    name: 'Tenth Floor St James Hall',
    url: 'https://www.tenstjames.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 12,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['succession', 'trusts & super', 'defamation & media', 'tax', 'IP'],
    notes: 'Small, high-seniority (3 SC of 12).',
  },
  {
    slug: 'sir-anthony-mason',
    name: 'Sir Anthony Mason Chambers',
    url: 'https://www.siranthonymason.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 28,
    emailExposure: 'profile',
    renderer: 'static',
    notes: 'Squarespace, flat root slugs. Intermittent robots.txt 429 — backoff handles it.',
  },
  {
    slug: 'denman',
    name: 'Denman Chambers',
    url: 'https://www.denmanchambers.com.au',
    listingPaths: ['/barristers'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 11,
    emailExposure: 'profile',
    renderer: 'static',
    focus: ['criminal', 'discrimination', 'employment'],
  },
  {
    slug: 'ada-evans',
    name: 'Ada Evans Chambers',
    url: 'https://www.adaevanschambers.com',
    listingPaths: ['/barristers', '/'],
    profilePattern: '^/[a-z0-9-]+$',
    region: 'sydney-cbd',
    approxCount: 10,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Founded 1998, named for the first woman law graduate in NSW.',
  },
  {
    slug: '153-phillip',
    name: '153 Phillip Barristers',
    url: 'https://153phillip.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 18,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Newer set.',
  },
  {
    slug: 'henry-parkes',
    name: 'Henry Parkes Chambers',
    url: 'https://www.henryparkes.com.au',
    listingPaths: ['/the-barristers/'],
    profilePattern: '^/the-barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 24,
    emailExposure: 'profile',
    renderer: 'static',
    focus: ['criminal'],
  },
  {
    slug: 'samuel-griffith',
    name: 'Samuel Griffith Chambers',
    url: 'https://www.samuelgriffithchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 39,
    emailExposure: 'profile',
    renderer: 'static',
    focus: ['criminal'],
    notes: 'Listing shows call year and has seniority filters. Some members use personal ISP addresses — MX-verify carefully.',
  },
  {
    slug: 'seven-windeyer',
    name: 'Seven Windeyer Chambers',
    url: 'https://sevenwindeyer.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/people/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 14,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Listing /barristers/, profiles /people/.',
  },
  {
    slug: '7-wentworth-selborne',
    name: 'Seven Wentworth Selborne',
    url: 'https://www.7thfloor.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+$',
    region: 'sydney-cbd',
    approxCount: 50,
    emailExposure: 'clerk-only',
    renderer: 'static',
  },
  {
    slug: 'sir-owen-dixon',
    name: 'Sir Owen Dixon Chambers',
    url: 'https://sirowendixon.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+$',
    region: 'sydney-cbd',
    approxCount: 87,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['criminal', 'appellate', 'common law'],
    notes: 'Three locations: Sydney, Newcastle, Wollongong. Largest multi-region set.',
  },
  {
    slug: 'university-chambers',
    name: 'University Chambers',
    url: 'https://www.universitychambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 65,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: '9 SC. Commercial-leaning, 25 practice areas.',
  },
  {
    slug: 'windeyer-8',
    name: 'Eight Windeyer Chambers',
    url: 'https://windeyer8.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Same building as the NSW Land & Environment Court — likely P&E-heavy.',
  },
  {
    slug: 'black-chambers',
    name: 'Black Chambers',
    url: 'https://blackchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 25,
    emailExposure: 'none',
    renderer: 'static',
    focus: ['criminal', 'mental health', 'human rights', 'police accountability'],
    notes: 'Publishes NO email anywhere — phone only. Kept in the registry so the crawler records the finding rather than us re-checking each run.',
  },
  {
    slug: 'trust-chambers',
    name: 'Trust Chambers',
    url: 'https://trustchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 30,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'No per-barrister pages — weak personalisation target even if addresses are found.',
  },
  {
    slug: 'sir-james-martin',
    name: 'Sir James Martin Chambers',
    url: 'https://sirjamesmartin.com',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 30,
    emailExposure: 'unknown',
    renderer: 'js',
    notes: 'Listing returned prose only in discovery — may be JS-rendered. Playwright path.',
  },
  {
    slug: 'level-22',
    name: 'Level 22 Chambers',
    url: 'https://level22.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    emailExposure: 'unknown',
    renderer: 'js',
    notes: 'Gatsby SPA — server returns meta tags only. Requires Playwright. Well-regarded commercial set; @level22.com.au confirmed.',
  },
  {
    slug: 'edmund-barton',
    name: 'Edmund Barton Chambers (Sydney)',
    url: 'https://ebc44.com',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    approxCount: 50,
    emailExposure: 'unknown',
    renderer: 'static',
    notes: 'NAME COLLISION: edmundbartonchambers.com.au is the ADELAIDE set. This one (ebc44.com) is Sydney, L44 MLC Centre.',
  },
  {
    slug: '8-garfield-barwick',
    name: 'Eight Garfield Barwick Chambers',
    url: 'https://www.8garfieldbarwick.com.au',
    listingPaths: ['/'],
    profilePattern: '^/(barristers|counsel)/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    emailExposure: 'clerk-only',
    renderer: 'static',
    skip: true,
    skipReason: 'Single-page site; barristers live under a homepage anchor with no per-barrister URLs. Manual pass only.',
  },
  {
    slug: '13-st-james',
    name: 'Thirteenth Floor St James Hall',
    url: 'https://13stjames.net.au',
    listingPaths: ['/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'sydney-cbd',
    emailExposure: 'unknown',
    renderer: 'static',
    skip: true,
    skipReason: 'No browsable index — profiles reachable only via a name/practice-area search form. Manual pass only.',
  },

  // ---------------------------------------------------------------------
  // TIER 4 — Parramatta, Newcastle, Wollongong, regional NSW.
  // Highest conversion odds: least likely to hold Westlaw/Lexis seats,
  // where per-head licensing is worst.
  // ---------------------------------------------------------------------
  {
    slug: 'lachlan-macquarie',
    name: 'Lachlan Macquarie Chambers',
    url: 'https://www.lacmac.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/profile/[a-z0-9-]+/?$',
    region: 'parramatta',
    approxCount: 27,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Largest Parramatta set. 16 George St.',
  },
  {
    slug: 'arthur-phillip',
    name: 'Arthur Phillip Chambers',
    url: 'https://www.apchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers/[a-z0-9-]+/?$',
    region: 'parramatta',
    emailExposure: 'unknown',
    renderer: 'static',
    focus: ['family', 'child welfare', 'criminal', 'commercial', 'civil'],
    notes: 'Est. 1989. Legal aid + Independent Children\'s Lawyer work.',
  },
  {
    slug: 'western-sydney-chambers',
    name: 'Western Sydney Chambers',
    url: 'https://westernsydneychambers.com',
    listingPaths: ['/barristers/', '/about/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'parramatta',
    emailExposure: 'none',
    renderer: 'static',
    focus: ['criminal'],
    notes: 'Accepts direct access. Contact form only.',
  },
  {
    slug: 'hunter-street',
    name: 'Hunter Street Chambers',
    url: 'https://www.hunterstreetchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'newcastle',
    approxCount: 11,
    emailExposure: 'clerk-only',
    renderer: 'static',
    notes: 'Their Wagga/Albury/Dubbo/Tamworth pages are SEO landing pages, not physical chambers — do not treat as separate targets.',
  },
  {
    slug: 'sir-james-dowling',
    name: 'Sir James Dowling Chambers',
    url: 'https://sirjamesdowlingchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barrister/[a-z0-9-]+/?$',
    region: 'newcastle',
    approxCount: 11,
    emailExposure: 'none',
    renderer: 'static',
    focus: ['family', 'PI', 'criminal', 'ADR'],
  },
  {
    slug: 'bolton-street',
    name: 'Bolton Street Chambers',
    url: 'https://boltonstreetchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'newcastle',
    approxCount: 6,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['family', 'equity & trusts', 'ADR', 'WHS', 'coronial', 'contested wills'],
    notes: 'Founded April 2024 — newest set in the registry, most likely to still be choosing tooling.',
  },
  {
    slug: 'atticus',
    name: 'Atticus Chambers',
    url: 'https://www.atticuschambers.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'newcastle',
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['criminal'],
  },
  {
    slug: 'hargrave',
    name: 'Hargrave Chambers',
    url: 'http://www.hargravechambers.com.au',
    listingPaths: ['/about-us', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'wollongong',
    approxCount: 3,
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['PI compensation', 'workers comp', 'motor accidents'],
  },
  {
    slug: 'lismore',
    name: 'Lismore Chambers',
    url: 'https://www.lismorechambers.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'regional-nsw',
    approxCount: 3,
    emailExposure: 'none',
    renderer: 'static',
    focus: ['criminal', 'coronial', 'Mental Health Tribunal', 'administrative'],
    notes: 'Publishes mobiles rather than email. Oldest chambers in the Northern Rivers.',
  },
  {
    slug: 'cb-chambers',
    name: 'CB Chambers (Commercial Bank Chambers)',
    url: 'https://cbchambers.com.au',
    listingPaths: ['/barristers/'],
    profilePattern: '^/barristers?/[a-z0-9-]+/?$',
    region: 'regional-nsw',
    emailExposure: 'clerk-only',
    renderer: 'static',
    focus: ['building & construction', 'care & protection', 'commercial', 'employment', 'succession', 'workers comp'],
    notes: 'Broadest regional practice mix — 20 areas. Lismore.',
  },
  {
    slug: 'orange-chambers',
    name: 'Orange Chambers',
    url: 'https://www.orangechambers.com.au',
    listingPaths: ['/barristers/', '/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'regional-nsw',
    approxCount: 5,
    emailExposure: 'none',
    renderer: 'static',
    notes: 'Includes two former judges. Central West.',
  },
  {
    slug: 'gosford-chambers',
    name: 'Gosford Chambers',
    url: 'https://gosfordchambers.com.au',
    listingPaths: ['/'],
    profilePattern: '^/[a-z0-9-]+/?$',
    region: 'regional-nsw',
    approxCount: 1,
    emailExposure: 'unknown',
    renderer: 'static',
    notes: 'Would not serve to automated fetch during discovery — verify manually.',
  },
];

/**
 * Chambers known to exist with no public website (per the NSW Barristers'
 * Clerks Association roll). Recorded so they are not silently missing from
 * coverage maths. Reachable by phone through their clerk only.
 */
export const NO_WEBSITE_CHAMBERS = [
  { name: 'Second Floor Wentworth', phone: '02 9232 4466', note: 'Facebook page only' },
  { name: 'Fourth Floor Wentworth', phone: '02 9232 2722' },
  { name: 'Fifth Floor Wentworth', phone: '02 8815 9111' },
  { name: 'Fifth Floor Selborne', phone: '02 9235 1155' },
  { name: 'Elizabeth Street Chambers', phone: '02 9336 5399' },
  { name: 'Queens Square Chambers', phone: '02 9232 4671' },
  { name: 'P G Hely Chambers', phone: '02 9224 9755' },
  { name: 'William Deane Chambers', phone: '02 9231 0077' },
  { name: 'Blackstone Chambers', note: 'LinkedIn only' },
  { name: 'Coffs Harbour Chambers', phone: '02 6652 8955', note: 'clerk Rose Roser' },
];

export const ACTIVE_CHAMBERS = CHAMBERS.filter((c) => !c.skip);
